apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jail-pvc-dupe
  namespace: test
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Ti
  volumeName: jail-pv-dupe
  storageClassName: slurm-local-pv

