apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jail-pvc-dupe2
  namespace: vllm
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Ti
  volumeName: jail-pv-dupe2
  storageClassName: slurm-local-pv

