---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jail-pvc-dupe2
  namespace: vllm
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Ti
  volumeName: jail-pv-dupe2
  storageClassName: slurm-local-pv
---
apiVersion: v1
kind: Service
metadata:
  name: vllm-base
  namespace: vllm
  labels:
    app: vllm
    model: base
    role: server
spec:
  type: LoadBalancer
  selector:
    app: vllm
    model: base
    role: server
  ports:
    - name: http
      port: 80
      targetPort: 8000
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vllm-base
  namespace: vllm
  labels:
    app: vllm
    model: base
    role: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vllm
      model: base
      role: server
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: vllm
        model: base
        role: server
    spec:
      runtimeClassName: nvidia
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: nvidia.com/gpu.product
                    operator: In
                    values:
                      - NVIDIA-H100-80GB-HBM3
      tolerations:
        - key: "slurm.nebius.ai/nodeset"
          operator: "Exists"
          effect: "NoSchedule"
      containers:
        - name: vllm
          image: vllm/vllm-openai:v0.10.0
          imagePullPolicy: IfNotPresent
          command: ["vllm", "serve", "/mnt/jail/basemodel",
                    "--served-model-name", "basemodel",
                    "--dtype", "bfloat16",
                    "--host", "0.0.0.0", "--port", "8000"]
          ports:
            - name: http
              containerPort: 8000
          resources:
            requests:
              cpu: "4"
              memory: "16Gi"
              nvidia.com/gpu: "1"
            limits:
              cpu: "4"
              memory: "16Gi"
              nvidia.com/gpu: "1"
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 10
            failureThreshold: 3
          volumeMounts:
            - name: jail-vol
              mountPath: /mnt/jail
              #changed from true
              readOnly: false
      volumes:
        - name: jail-vol
          persistentVolumeClaim:
            claimName: jail-pvc-dupe2

